Anchors hint
Kotlin/dokka pull request #1307
Opened 2020-08-13 15:53 UTC by MarcinAman

2020-08-13 15:54 UTC, MarcinAman commented on plugins/base/src/main/resources/dokka/scripts/platformContentHandler.js
> +            const content = element.nextElementSibling
This change is unrelated to anchors rendering, but I saw that anchors are not highlighted correctly when there is no tab (eg. on module page)

2020-08-20 14:08 UTC, Kordyjan requested changes
In my opinion this pr should add potential anchors for all table rows. Of course, I'm open for discussion.

2020-09-01 15:25 UTC, MarcinAman commented
> In my opinion this pr should add potential anchors for all table rows. Of course, I'm open for discussion.

I thought about it and i don't see a reason why we should preemptively generate anchors. Also this is super bad in current state since anchors are not unique (see https://github.com/Kotlin/dokka/issues/1258 and anchors don't have a sourceset in them so every sourceset tab would be broken). Using an extra is a decent idea since it gives us control over what we want to link to and introduces a straight forward logic how to do it.

2020-10-02 14:04 UTC, BarkingBad reviewed
I think currently we currently generate anchors for every element possible (I think I added that to handle typealiases and properties (which will have their own pages since #1494)) so we should check that PR for any possible inconvenient behaviour.

2020-10-08 15:06 UTC, kamildoleglo approved these changes

2020-10-08 16:54 UTC, kamildoleglo approved these changes

2020-10-08 17:05 UTC, merged