Render react resources as separate css to allow overriding
Kotlin/dokka pull request #1416
Opened 2020-08-31 15:43 UTC by MarcinAman

2020-09-03 12:56 UTC, MarcinAman commented
Given our current dsl is there any way to test it?

2020-09-08 09:58 UTC, MarcinAman commented
/rebase

2020-09-08 13:04 UTC, Kordyjan requested changes

2020-09-08 13:04 UTC, Kordyjan commented on plugins/base/build.gradle.kts
> +task("copy_frontend") {
Why not `by registering`?

2020-09-14 07:09 UTC, MarcinAman commented
Rebased

2020-10-02 13:51 UTC, BarkingBad approved these changes

2020-10-05 08:24 UTC, merged