Make logo replaceable #1339
Kotlin/dokka pull request #1488
Opened 2020-09-18 12:52 UTC by MarcinAman

2020-09-22 11:59 UTC, BarkingBad approved these changes
Maybe we should update user manual with info about extending custom styles and assets

2020-09-24 09:07 UTC, kamildoleglo requested changes
Also you forgot to update Maven configuration

2020-09-24 09:07 UTC, kamildoleglo commented on runners/cli/src/main/kotlin/cli/main.kt
> +        get() = "{ String thar represents platform }"
`thar` -> `that`

2020-10-06 13:39 UTC, kamildoleglo approved these changes

2020-10-07 11:58 UTC, merged