Adding separate pages for properties
Kotlin/dokka pull request #1494
Opened 2020-09-21 08:08 UTC by sellophane

2020-10-02 10:07 UTC, BarkingBad approved these changes

2020-10-05 09:43 UTC, kamildoleglo requested changes

2020-10-05 09:43 UTC, kamildoleglo commented on plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
> +                is DProperty -> element.copy(name = element.toClashedName())
Typealiases can also clash

2020-10-06 13:40 UTC, kamildoleglo approved these changes

2020-10-06 13:41 UTC, merged