Fix multiline links in javadoc
Kotlin/dokka pull request #1518
Opened 2020-10-01 07:58 UTC by BarkingBad

```
/**
 * Here comes some comment
 *
 * {@link example.SomeClassToLink#someFunc(int, Object) someName(ads,
 * dsa)}
 *
 * longer comment
 */
public class SomeJavaDocExample {
}
```

![obraz](https://user-images.githubusercontent.com/32793002/94783144-8be22f00-03cc-11eb-8db9-487931a4303d.png)

2020-10-04 15:55 UTC, sellophane approved these changes

2020-10-06 12:04 UTC, kamildoleglo requested changes

2020-10-06 12:04 UTC, kamildoleglo commented on plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/location/JavadocLinkingTest.kt
> +                        externalLink("https://docs.oracle.com/javase/8/docs/api/"),
We should have helpers for those links

2020-10-07 15:07 UTC, MarcinAman commented on plugins/base/src/main/kotlin/translators/psi/JavadocParser.kt
> +                """<a data-dri=$dri>${label.joinToString(" ") { it.text }}</a>"""
to do that we would need to have a dri for that, which in this case is not possible

2020-10-08 18:25 UTC, merged