Add more specific instruction on applying plugins
Kotlin/dokka pull request #1579
Opened 2020-10-19 08:02 UTC by MarcinAman

2020-10-19 13:07 UTC, kamildoleglo requested changes

2020-10-19 13:07 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/gradle/usage.md
> +In order to apply a plugin add it in `dependencies` block:
```suggestion
In order to apply a plugin add it in the `dependencies` block:
```

2020-10-19 13:07 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/gradle/usage.md
> +Keep in mind, that plugins developed by the community may not follow same convention. Always consult plugin's creator documentation.
```suggestion
!!! important
    Keep in mind that plugins developed by the community may not follow the same convention. Always consult the plugin's documentation.
```

2020-10-19 13:07 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/plugins-specific/base-specific/frontend.md
> + * `jetbrains-mono.css` - fonts used across dokka
```suggestion
 * `jetbrains-mono.css` - fonts used across Dokka
```

2020-10-19 13:07 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/plugins-specific/index.md
> +Base, GFM and Jekyll plugins are applied by default. Rest of those needs to be applied manually.
```suggestion
Base, GFM, and Jekyll plugins are applied by default. The rest of those need to be applied manually. 
```

2020-10-20 08:31 UTC, MarcinAman commented on docs/src/doc/docs/user_guide/gradle/usage.md
> +| Plugin name    | Dependency                                         | Added tasks  |
This is a dependency that would need to be added to the build in order to use this feature not a plugins hierarchy

2020-10-20 08:40 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/gradle/usage.md
> +| Plugin name    | Dependency                                         | Added tasks  |
Yes, but `Dependency` looks like its the only dependency of the plugin, which is not true

2020-10-29 16:09 UTC, MarcinAman commented on docs/src/doc/docs/user_guide/gradle/usage.md
> +| Plugin name    | Dependency                                         | Added tasks  |
applied with

2020-11-14 00:21 UTC, kamildoleglo approved these changes

2023-02-23 04:31 UTC, IgnatBeresnev commented
The documentation was re-written and is now published to kotlinlang.org. There's a section on Dokka plugins and how to apply them: https://kotlinlang.org/docs/dokka-plugins.html

Closing the PR as implemented / outdated

2023-02-23 04:31 UTC, closed without merging