Create documentation for versioning
Kotlin/dokka pull request #1748
Opened 2021-02-12 10:22 UTC by MarcinAman

2021-02-12 13:26 UTC, MarcinAman commented
@kamildoleglo should we state that for now it is only available for mutlimodule or just try to make it happen before the release ?

2021-02-15 10:58 UTC, kamildoleglo requested changes

2021-02-15 10:58 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/versioning/versioning.md
> +Versioning plugin is enabled by default in dokka so there is no need to apply it manually.
dokka -> Dokka

Maybe "is applied by default but not enabled" or similar?

2021-02-15 10:58 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/versioning/versioning.md
> +* olderVersionsDir - an optional file that represents the parent directory containing folders with previous dokka outputs.
dokka -> Dokka

2021-02-15 10:58 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/versioning/versioning.md
> +  By default, dokka will try to use semantic versioning to create such ordering.
dokka -> Dokka

2021-02-15 10:58 UTC, kamildoleglo commented on docs/src/doc/docs/user_guide/versioning/versioning.md
> +As can be seen on the diagram, `olderVersionsDir` should be a parent directory of previous output directories.
I'd also include a example configuration eg. for Gradle

2021-02-15 10:59 UTC, kamildoleglo commented
I'd state that it will only work for multimodule for now and fix it in the next release

2021-03-01 11:01 UTC, merged