Description list support for JavaDocs (#2213)
Kotlin/dokka pull request #2259
Opened 2021-12-06 13:23 UTC by IgnatBeresnev

2021-12-06 13:24 UTC, IgnatBeresnev commented on core/src/main/kotlin/pages/ContentNodes.kt
> +    DescriptionDetails
I thought about extracting it to a separate enum `ListContentStyle`, but it seems unlikely that we'll ever add anything else there, so probably not worth it?

2021-12-06 22:21 UTC, vmishenev requested changes
* This does not work with:
```
<dl>
    <div>
        <dt>Term1</dt>
        <dd>Desc2</dd>
    </div>
    <div>
        <dt>Term2</dt>
        <dd>Desc2</dd>
    </div>
</dl> 
```
* What is about another tags, e.g. `dfn`?

2021-12-06 22:21 UTC, vmishenev commented on plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt
> +                    if (newStyles.isEmpty()) styles else styles + newStyles,
Why!? It is not essential optimization.

2021-12-07 11:23 UTC, IgnatBeresnev commented
> This does not work with:
> ```
> <dl>
>   <div>
>        <dt>Term1</dt>
>        <dd>Desc2</dd>
>    </div>
>    <div>
>        <dt>Term2</dt>
>        <dd>Desc2</dd>
>    </div>
> </dl> 
> ```

Unfortunately, it seems to be the limitation of the content model in general since there's no separate content type for list items, which are now handled as `ContentGroup`. For instance, for `ul/ol`, we consider all children to be `li`, even if they're not. In javadocs it results in this
```
    /**
     * <ul>
     *     <div>one</div>
     *     <div>two</div>
     * </ul>
     */
```
being rendered as
* one
* two

__________________

As for description lists, `dl` is `ContentList` and `dt/dd` are `ContentGroup` with a list style, and just like for `ol/ul`, I only look for list items among the top level children. If we want to be able to render nested `dd/dt` using the current content model, I see the following options:
* Map `dt/dd` into `ContentList` (but this won't work for `ol/ul` due to nested lists)
* Add an `if (node.hasStyle(DescriptionTag))` into `buildGroup`

And I don't like either solution :)

We could extend the content model and introduce `ContentListItem` and render it separately, but I would expect you not to like it ;)

All in all, I don't see an easy way out, let me know if you do. Hopefully your example is a rare case and the solution can be postponed

2021-12-07 11:29 UTC, IgnatBeresnev commented
> What is about another tags, e.g. dfn?

It seems like `dfn` can indeed be used within description lists, but it's not exclusive to that, so I think it falls more under "support more javadoc html tags", which I indeed didn't do. We can plan it as a separate issue/pr

2021-12-07 12:13 UTC, vmishenev commented on plugins/base/src/main/kotlin/transformers/pages/comments/DocTagToContentConverter.kt
> +                    if (newStyles.isEmpty()) styles else styles + newStyles,
Anyway this  is not a good place for optimization. It is an issue of implementation of `plus`. 

This make code more complex to read and can consider as boilerplate.

2021-12-07 12:13 UTC, vmishenev commented on plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
> +    ) {
Please make the all three. Unfortunately code is not ideal. Our goal is to make it better.

2021-12-07 12:24 UTC, vmishenev commented
> It seems like dfn can indeed be used within description lists, but it's not exclusive to that
It is a good case to think about the design of styles beforehand.

> We can plan it as a separate issue/pr
Can you open an issue for it?

2021-12-07 14:00 UTC, vmishenev commented
```
    /**
     * <ul>
     *     <div>one</div>
     *     <div>two</div>
     * </ul>
     */
```
It is impossible for HTML scheme.
See https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element

2021-12-07 14:35 UTC, IgnatBeresnev commented on plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
> +    ) {
> Unfortunately code is not ideal. Our goal is to make it better.

Making everything into a single expression function is not making the code better, it's subjective and is purely about projects style guide :)

I tried making the other two into single-expression, but the compiler's not able to infer types properly and you have you specify it explicitly. I'm sorry, but this looks worse:
```
    open fun DL.buildListItems(
        items: List<ContentNode>,
        pageContext: ContentPage,
        sourceSetRestriction: Set<DisplaySourceSet>? = null
    ): Unit = items.forEach {
``` 
Let's leave it as it is

2021-12-09 10:23 UTC, vmishenev approved these changes
Please add my case to tests

2021-12-14 07:09 UTC, merged