Add a distinct divider between function overloads
Kotlin/dokka pull request #2585
Opened 2022-07-25 16:26 UTC by IgnatBeresnev

2022-07-25 16:37 UTC, IgnatBeresnev commented on plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
> -
Unused

2022-07-25 16:38 UTC, IgnatBeresnev commented on plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt
> +    private fun groupDivergentInstancesWithSourceSet(
This made `buildDivergent` considerably longer, even though this particular function needed no context from it and shared nothing in common, so I don't see a reason why it has to be a nested function.

Extracted for the sake of readability of `buildDivergent`

2022-07-26 16:31 UTC, IgnatBeresnev commented
Proposing to go with this solution as it adds no new public API, so it will be easy to remove when the page is redesigned, which is just a matter of time.

I'll post the final result to #kotlin-libs and ask for feedback. If this version is not liked for some reason, it can be changed before release

2022-07-27 19:26 UTC, vmishenev requested changes
1. https://dokka-snapshots.s3.eu-central-1.amazonaws.com/fuction-overloads-dinstinct/serialization/8779f50/kotlinx-serialization-core/kotlinx.serialization.builtins/serializer.html 
There are not overloads.
2. Regression: There is extra space in a declaration list. It requires a check `node.dci.kind == ContentKind.Main` that it is removed in this PR.

![image](https://user-images.githubusercontent.com/9636937/181355211-108efed4-2105-45d0-b5e9-e308608d2a71.png)

2022-07-27 21:35 UTC, IgnatBeresnev commented
> There are not overloads.

Not sure what you mean. These are different functions with different description, but with the same function name, so for me it makes an overload :thinking:

2022-07-27 23:18 UTC, vmishenev commented
> Not sure what you mean. These are different functions with different description, but with the same function name, so for me it makes an overload thinking

Sorry(  I wrote a wrong sentence.

For https://dokka-snapshots.s3.eu-central-1.amazonaws.com/fuction-overloads-dinstinct/stdlib/4ce210b/kotlin-stdlib/kotlin.collections/indices.html, that has several extension properties﻿, it does not have a divider.

2022-07-28 00:26 UTC, IgnatBeresnev commented
> has several extension properties

Silly me, for some reason I thought class named `Same**Method**NamePageMergerStrategy` only merged methods :smiling_face_with_tear:

Previously there was a check that it was only functions, changed it to accept for all members, so both functions and properties.

2022-08-04 12:30 UTC, IgnatBeresnev commented
After some discussion, we decided to drop "Overload" header and just stick with a simple horizontal line

Updated the PR, @vmishenev please have a look

2022-08-04 13:24 UTC, vmishenev approved these changes

2022-08-05 11:25 UTC, merged