Apply the same style to all KDoc tags, including throws/see/parameters
Kotlin/dokka pull request #2587
Opened 2022-07-26 20:56 UTC by IgnatBeresnev

See https://github.com/Kotlin/dokka/issues/2576

* Now all KDoc tag sections should look the same, including throws/see/parameters
* Decreased space between tag header and values

* Fixed a problem where longer link text had many word breaks:
    * See/Throws link text is now just the class name (if DRI is resolved), full path if unresolved; previously always full path
    * Increased first column width for See/Throws/Parameters a bit.
    * (I have a complete JS script to dynamically adjust the width of the first column based on link width, will discuss it during sync and maybe file it as another PR)

2022-07-27 19:47 UTC, vmishenev requested changes
Before:
![image](https://user-images.githubusercontent.com/9636937/181359111-1468b073-5b0b-4801-b203-3a176aba306d.png)
After:
![image](https://user-images.githubusercontent.com/9636937/181359239-e08d5f83-cb3b-479f-9dd2-c94b96f155e2.png)

2022-07-27 19:47 UTC, vmishenev commented on plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
> +                header(4, "Parameters", kind = ContentKind.Parameters, sourceSets = availablePlatforms)
I think it is better to make a constant to avoid magic number.

2022-07-27 19:47 UTC, vmishenev commented on plugins/base/src/main/kotlin/translators/documentables/DefaultPageCreator.kt
> +                                            if (it.root.children.isNotEmpty()) {
I would create a helper like `TagWrapper.isEmpty() = children.isEmpty()` (Law of Demeter)

2022-07-27 22:11 UTC, IgnatBeresnev commented
> After (there is space after Return)

I've fixed `Since Kotlin` block, totally forgot about that :+1: but I don't understand what's wrong with `Return`

2022-07-28 13:35 UTC, vmishenev approved these changes

2022-08-03 11:51 UTC, merged