Re-implement enum documentation test
Kotlin/dokka pull request #3762
Opened 2024-08-26 11:27 UTC by adam-enko

Re-implement the enum documentation test to download and use the actual Kotlin stdlib enum source code for the synthetic enum functions.

This avoids hardcoding a URL, and helps ensure the tests are properly cacheable (so they don't dynamically download files at runtime).

- Add a utility, `downloadKotlinStdlibSources()`, to download the Kotlin stdlib source code.
- Move StdLibDocumentationIntegrationTest.kt to plugin-base since it's not really an integration test, and otherwise it's hard to access the actual enum template files.
- Update the enum template tests to test all templates.

2024-08-27 12:02 UTC, whyoleg requested changes
Thanks!
The approach looks good to me, the only problem I see is with version of stdlib which is used for comparing.
We used `master` version, but now we will use some specific version, so we will lag behind a bit. Not sure it will really matter.

2024-08-27 12:27 UTC, adam-enko commented on build-logic/src/main/kotlin/dokkabuild/utils/downloadKotlinStdlibJvmSources.kt
> +            add(project.dependencies.run { create(kotlin("stdlib")) })
The same as KGP.

(Technically it adds a dependency with no version, and then KGP automatically aligns `org.jetbrains.kotlin` dependencies.)

2024-08-27 12:28 UTC, adam-enko commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +     * The Dokka template didn't match the stdlib source code when this test was created.
So should the test be deleted or `@Ignored`?

2024-08-27 12:33 UTC, adam-enko commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +            kotlinStdlibSourcesDir.resolve("jvmMain/kotlin/Enum.kt")
I couldn't find any references to enums in `commonMain`.

By 'check both', do you mean also download the stdlib-common sources? There's no `Enum.kt` in there, only `EnumEntries.kt`, and it's the same as the file in the stdlib-jvm sources.

2024-08-27 12:38 UTC, whyoleg commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +            kotlinStdlibSourcesDir.resolve("jvmMain/kotlin/Enum.kt")
Okay, never mind, looks like we have `Enum.kt` only in platform jars. Should be fine to check just this one.

2024-08-27 12:40 UTC, whyoleg commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +     * The Dokka template didn't match the stdlib source code when this test was created.
would be nice to have it `@Ignored` with the content as in `enumValues` and a link to this YT issue

2024-08-28 09:15 UTC, IgnatBeresnev commented
> Move StdLibDocumentationIntegrationTest.kt to plugin-base since it's not really an integration test, and otherwise it's hard to access the actual enum template files.

For context: I added it as an integration test became it made a network request that could hang, return an error or produce unexpected results. That's somewhat expected from integration (e2e) tests, but I certainly wouldn't expect unit tests to fail if GitHub is down

2024-08-29 10:05 UTC, dkrasnoff approved these changes

2024-08-29 10:05 UTC, dkrasnoff commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +            assertSubstringIsInFiles(line, enumValuesTemplate, actualStdlibEnumKt)
nit: enumValuesTemplate -> enumEntriesTemplate?

2024-08-29 10:06 UTC, dkrasnoff commented
Good job! 👍

2024-08-29 10:27 UTC, adam-enko commented on build-logic/src/main/kotlin/dokkabuild/utils/downloadKotlinStdlibJvmSources.kt
> +        into(temporaryDir)
Hmm, interesting, it looks like there's a bug in the rendered Dokka. It's not showing the kdoc from the override.

https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api/-task/get-temporary-dir.html

> Returns a directory which this task can use to write temporary files to. Each task instance is provided with a separate temporary directory. There are no guarantees that the contents of this directory will be kept beyond the execution of the task.

2024-08-29 10:29 UTC, adam-enko commented on dokka-subprojects/plugin-base/src/test/kotlin/EnumTemplatesTest.kt
> +            assertSubstringIsInFiles(line, enumValuesTemplate, actualStdlibEnumKt)
thanks!

```suggestion
            assertSubstringIsInFiles(line, enumEntriesTemplate, actualStdlibEnumKt)
```

2024-08-29 10:39 UTC, dkrasnoff commented on build-logic/src/main/kotlin/dokkabuild/utils/downloadKotlinStdlibJvmSources.kt
> +        into(temporaryDir)
Oh, I see, thanks!
This sentence makes me a little bit concerned: "There are no guarantees that the contents of this directory will be kept beyond the execution of the task", but it works 🤷

2024-08-29 10:43 UTC, adam-enko commented on build-logic/src/main/kotlin/dokkabuild/utils/downloadKotlinStdlibJvmSources.kt
> +        into(temporaryDir)
I think that warning is supposed to mean "the temporary directory is in the `build/` directory, which can be regularly cleaned or git-ignored."

2024-08-29 12:30 UTC, merged