remove usage of user/password for build cache
Kotlin/dokka pull request #3818
Opened 2024-09-20 14:58 UTC by whyoleg

as per https://jetbrains.slack.com/archives/C02H0GSH474/p1726843809954669

2024-09-23 06:05 UTC, adam-enko approved these changes

2024-09-23 06:06 UTC, adam-enko reviewed
```

FAILURE: Build failed with an exception.

* Where:
Script '/home/runner/work/dokka/dokka/build-settings-logic/src/main/kotlin/dokkasettings.build-cache.settings.gradle.kts' line: 47

* What went wrong:
Script compilation errors:

  Line 47:     remote(develocity.buildCache) {
               ^ Not enough information to infer type variable T

  Line 47:     remote(develocity.buildCache) {
                      ^ Unresolved reference: develocity

  Line 48:         isPush = buildCachePushEnabled.get()
                   ^ Variable expected

3 errors
```

2024-09-23 06:14 UTC, adam-enko requested changes
```

FAILURE: Build failed with an exception.

* Where:
Script '/home/runner/work/dokka/dokka/build-settings-logic/src/main/kotlin/dokkasettings.build-cache.settings.gradle.kts' line: 47

* What went wrong:
Script compilation errors:

  Line 47:     remote(develocity.buildCache) {
               ^ Not enough information to infer type variable T

  Line 47:     remote(develocity.buildCache) {
                      ^ Unresolved reference: develocity

  Line 48:         isPush = buildCachePushEnabled.get()
                   ^ Variable expected

3 errors
```

2024-09-24 10:43 UTC, whyoleg commented
Will be resolved in https://github.com/Kotlin/dokka/pull/3825

2024-09-24 10:43 UTC, closed without merging