Filter non-directory and hidden files from version directories
Kotlin/dokka pull request #3973
Opened 2024-12-22 01:22 UTC by jeffdgr8

Fixes #3963

2025-01-16 14:20 UTC, whyoleg requested changes
Thanks!
Could you please check the comment?

2025-01-16 14:20 UTC, whyoleg commented on dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/VersioningConfiguration.kt
> +            ?.filter { it.isDirectory && !it.isHidden }
Do we really need to filter out `hidden` directories here? Their definition is a bit vague, and I think that getting just directories should be enough.

If you think, that we should still filter out `hidden` directories for some reason, then it would be nice to add a comment for reasoning there.

2025-01-17 02:28 UTC, jeffdgr8 commented on dokka-subprojects/plugin-versioning/src/main/kotlin/org/jetbrains/dokka/versioning/VersioningConfiguration.kt
> +            ?.filter { it.isDirectory && !it.isHidden }
My reasoning was that typically a hidden directory wouldn't be used to store a versioned docs archive, but could be some system created or metadata directory. While .DS_Store was the cause of the issue I ran into and would be filtered out by just ignoring non-directory files, I was thinking there could be other hidden system or metadata files that are directories. An example might be .git or less likely .idea.

If you think it's more likely valid version directories actually are hidden, we could remove the `!it.isHidden` check. I'm fine either way.

2025-05-09 13:07 UTC, whyoleg approved these changes
Thanks!

2025-05-09 13:07 UTC, merged